---
- name: install ephemeris on virtualenv
  become: true
  become_user: galaxy
  pip:
    name:
      - ephemeris
      - bioblend
    virtualenv: '{{ laniakea_galaxy_venv_dir }}' 

- name: 'Check if {{ galaxy_tools_base_dir }} exist'
  stat:
    path: '{{ galaxy_tools_base_dir }}/Galaxy-flavours'
  register: tool_dir_path

- name: 'Create {{ galaxy_tools_base_dir }}'
  file:
    path: '{{ galaxy_tools_base_dir }}'
    state: directory
  when: not tool_dir_path.stat.exists|bool
  become_user: root
  become_method: sudo

- name: Get Galaxy flavor
  git:
    repo: '{{ galaxy_flavors_url }}'
    dest: '{{ galaxy_flavors_dir }}'
    version: '{{ galaxy_flavors_tag }}'
    clone: yes
    force: yes
  when: not tool_dir_path.stat.exists|bool
  become_user: root
  become_method: sudo
