---

- name: create admin user
  import_tasks: create_bootstrap_user.yml

- name: Flavor download
  import_tasks: get_flavor.yml

- name: Install tools
  import_tasks: tools.yml
  listen: "restart galaxy"

- name: Install workflows
  import_tasks: workflows.yml
  listen: "restart galaxy"
