---

- name: Template a file to /etc/file.conf
  template:
    src: laniakea_install_tools.sh.j2
    dest: "{{ laniakea_galaxy_server_dir }}/laniakea_install_tools.sh"
    owner: galaxy
    group: galaxy

- name: start galaxy No NGINX
  become: true 
  become_user: galaxy 
  shell:
    cmd: bash laniakea_install_tools.sh start 
    chdir: "{{ laniakea_galaxy_server_dir}}"
  ignore_errors: true

- name: Install flavor tools with ephemeris No NGINX running with custom script 
  become: true 
  become_user: galaxy 
  shell:
    cmd: bash laniakea_install_tools.sh install "{{ GALAXY_ADMIN_API_KEY }}"  "{{ item }}"
    chdir: "{{ laniakea_galaxy_server_dir}}"
  with_fileglob: 
    - '{{ galaxy_tools_base_dir }}/Galaxy-flavors-recipes/{{ laniakea_galaxy_flavor }}/*.yml'
  retries: 3
  delay: 3
  register: installation
  until: installation.rc == 0
  ignore_errors: true

- name: Install flavor tools with ephemeris No NGINX running with custom script DEBUG
  become: true 
  become_user: galaxy 
  shell:
    cmd: bash laniakea_install_tools.sh install "{{ GALAXY_ADMIN_API_KEY }}"  "{{ item }}"
    chdir: "{{ laniakea_galaxy_server_dir}}"
  with_fileglob: 
    - '{{ galaxy_tools_base_dir }}/Galaxy-flavors-recipes/{{ laniakea_galaxy_flavor }}/*.yml'
  retries: 3
  delay: 3
  register: installation
  until: installation.rc == 0
  when: role_debug == "true" 

- name: stop galaxy NO NGINX and restart GALAXY with NGINX
  become: true 
  become_user: galaxy 
  shell:
    cmd: bash laniakea_install_tools.sh stop 
    chdir: "{{ laniakea_galaxy_server_dir}}"
  ignore_errors: true

- name: check workflow flavor existence
  stat:
    path: '{{ galaxy_tools_base_dir }}/Galaxy-flavors-recipes/{{ laniakea_galaxy_flavor }}/workflows'
  register: workflows 

- name: Install workflows on GALAXY
  become: true
  become_user: galaxy
  shell: 
    cmd: . "{{ laniakea_galaxy_venv_dir }}/bin/activate";  galaxy-wait -g http://localhost:80 -v --timeout 120; workflow-install -a "{{ GALAXY_ADMIN_API_KEY }}" -w '{{ workflows.stat.path }}/' -g http://localhost:80 --publish_workflows
    executable: /bin/bash
  when: workflows.stat.exists == True

