

- name: Template a file to /etc/file.conf
  template:
    src: laniakea_install_tools.sh.j2
    dest: "{{ galaxy_run_sh_dir }}/laniakea_install_tools.sh"
    owner: galaxy
    group: galaxy

- name: Install flavor tools with ephemeris No NGINX running with custom script
  become: true 
  become_user: galaxy 
  shell:
    cmd: bash laniakea_install_tools.sh "{{ galaxy_admin_api_key }}"  "{{ item }}"
    chdir: "{{ galaxy_run_sh_dir}}"
  with_fileglob: '{{ galaxy_tools_base_dir }}/Galaxy-flavors-recipes/{{ laniakea_galaxy_flavor }}/*tool-list*'

- name: check workflow flavor existence
  stat:
    path: '{{ galaxy_tools_base_dir }}/Galaxy-flavors-recipes/{{ laniakea_galaxy_flavor }}/{{ laniakea_galaxy_flavor }}-workflows'
  register: workflow

- name: Install workflows with NGINX running
  become: true
  become_user: galaxy
  shell: 
    cmd: . "{{ galaxy_virtual_env }}/bin/activate";  galaxy-wait -g http://localhost:80 -v --timeout 120; workflow-install -a "{{ galaxy_admin_api_key }}" -w '{{ workflow.stat.path }}/' -g http://localhost:80 --publish_workflows
    executable: /bin/bash
  when: workflow.stat.exists == True

