---

- name: Template a file to /etc/file.conf
  template:
    src: laniakea_install_tools.sh.j2
    dest: "{{ laniakea_galaxy_server_dir }}/laniakea_install_tools.sh"
    owner: galaxy
    group: galaxy

- name: Get tool list name on remote
  find:
    path: '{{ galaxy_flavors_dir }}/{{ galaxy_flavor }}/'
    patterns: "*.yml,*.yaml"
  register: flavor_tool_lists

- name: Install flavor tools with ephemeris running with custom script 
  become: true 
  become_user: galaxy 
  shell:
    cmd: bash laniakea_install_tools.sh "{{ GALAXY_ADMIN_API_KEY }}" "{{ item.path }}"
    chdir: "{{ laniakea_galaxy_server_dir}}"
  with_items: "{{ flavor_tool_lists.files }}"
  retries: 3
  delay: 3
  register: installation
  until: installation.rc == 0
  ignore_errors: true
  when: not role_debug

- name: '[DEBUG] Install flavor tools with ephemeris running with custom script'
  become: true 
  become_user: galaxy 
  shell:
    cmd: bash laniakea_install_tools.sh "{{ GALAXY_ADMIN_API_KEY }}" "{{ item.path }}"
    chdir: "{{ laniakea_galaxy_server_dir}}"
  with_items: "{{ flavor_tool_lists.files }}"
  retries: 3
  delay: 3
  register: installation
  until: installation.rc == 0
  when: role_debug
