---
- name: Restart galaxy
  command: "{{ laniakea_galaxy_venv_dir }}/bin/galaxyctl -c {{ laniakea_galaxy_config_dir }}/galaxy_bootstrap.yml restart"
  become_user: root
  become_method: sudo
  listen: "restart galaxy"
